export const CLINIC = {
  name: 'Aayurphysio Wellness Centre',
  tagline: 'Pain to Power.',
  description: "Pune's first holistic physiotherapy and wellness hub — where evidence-based rehabilitation meets the healing wisdom of the body.",
  address: 'Plot No 606, Sector 25, Pradhikaran Nigdi, Near BHEL Chowk, Nigdi, Pune – 411044',
  phone: '+91 76669 26099',
  whatsapp: '+91 76669 26099',
  email: 'aayurphysio@gmail.com',
  hours: 'Mon–Sat: 9:00 am – 7:00 pm | Sunday: By Appointment Only',
  rating: '4.7',
  reviews: '22',
  experience: '15+',
  mapsUrl: 'https://maps.google.com/?q=Aayurphysio+Wellness+Centre+Nigdi+Pune',
  googleReviewsUrl: 'https://share.google/nWrkgnVON68mZFTre',
  mapsEmbed: '<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3780.1243840261086!2d73.76835997465533!3d18.65841356495023!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3bc2b9fa90cc7d29%3A0xe396e4202e4a5c20!2sAayurphysio%20Wellness%20Centre(%20Ayurveda%2C%20physiotherapy%2Cnutrition%20and%20yoga))!5e0!3m2!1sen!2sin!4v1780769196280!5m2!1sen!2sin" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>',
  whatsappMessage: 'Hi, I would like to book an appointment at Aayurphysio Wellness Centre.',
}

export const TEAM = [
  { name: 'Dr. Amruta Deshmukh', qualifications: 'BAMS, Ph.D', role: 'Ayurveda Physician & Sports Nutritionist', initials: 'AD', color: 'sage' },
  { name: 'Dr. Saurabh Deshmukh', qualifications: 'PT, BPTh', role: 'Orthopaedic Physiotherapist', initials: 'SD', color: 'terracotta' },
  { name: 'Dr. Amruta Potdar', qualifications: 'PT, BPTh, M.Sc', role: 'Orthopaedic Physiotherapist', initials: 'AP', color: 'bark' },
  { name: 'Dr. Pankaj Sharma', qualifications: 'MBBS, DNB', role: 'Orthopaedic Surgeon', initials: 'PS', color: 'sage' },
  { name: 'Priyanka Kalbhor', qualifications: '', role: 'ANC PNC Coach & Lactation Consultant', initials: 'PK', color: 'terracotta' },
  { name: 'Sayali Deshpande', qualifications: 'B.A Yoga Trainer', role: 'Yoga & Fitness Coach', initials: 'SD2', color: 'bark' },
  { name: 'Dr. Neelam Vedpathak', qualifications: 'BAMS, MD', role: 'Panchakarma Specialist', initials: 'NV', color: 'sage' },
  { name: 'Mr. Sumedh Joshi', qualifications: '', role: 'Fitness Coach', initials: 'SJ', color: 'terracotta' },
  { name: 'Dr. Bharati Deokar-Sharma', qualifications: '', role: 'Orthopaedic Surgeon', initials: 'BD', color: 'bark' },
]

export const SERVICES = [
  {
    id: 1,
    name: 'Orthopaedic Physiotherapy',
    description: 'Evidence-based treatment for joint, muscle and bone conditions — including knee, hip, shoulder and spine disorders. Our therapists use targeted manual therapy, exercise prescription and electrotherapy to restore strength and mobility without dependency on medication.',
    icon: 'bone',
    color: 'sage',
  },
  {
    id: 2,
    name: 'Sports Physiotherapy',
    description: 'Targeted rehabilitation for sports-related injuries using biomechanical analysis, sport-specific conditioning and return-to-play protocols. Suitable for amateur fitness enthusiasts and competitive athletes alike.',
    icon: 'activity',
    color: 'terracotta',
  },
  {
    id: 3,
    name: 'Neuro Physiotherapy',
    description: "Specialised rehabilitation for stroke, Parkinson's disease, multiple sclerosis and spinal cord injuries. Focused on rebuilding movement patterns, improving balance and restoring daily independence through progressive therapy.",
    icon: 'brain',
    color: 'bark',
  },
  {
    id: 5,
    name: 'Vertigo Assessment & Treatment',
    description: 'Specialised vestibular rehabilitation using BPPV repositioning manoeuvres (Epley, Semont) and balance retraining exercises. Effectively treats dizziness, positional vertigo and vestibular dysfunction — often resolving in just 1–3 sessions.',
    icon: 'rotate',
    color: 'terracotta',
  },
  {
    id: 7,
    name: 'Ayurveda & Panchakarma',
    description: 'Authentic Ayurvedic consultations and classical therapies designed to restore balance, promote natural healing, and enhance overall well-being. By combining traditional Ayurvedic wisdom with a personalised approach, we provide effective solutions for lifestyle disorders, pain management, detoxification, stress relief, women\'s health, and preventive healthcare — helping you achieve lasting health and vitality naturally.',
    icon: 'leaf',
    color: 'sage',
  },
  {
    id: 8,
    name: 'Sports Nutrition',
    description: 'Personalised, science-based nutritional guidance to support athletic performance, recovery, body composition, and overall health. Whether you are a professional athlete, fitness enthusiast, or recreational sportsperson, our customised nutrition plans help optimise energy levels, enhance endurance and strength, accelerate recovery, prevent injuries, and achieve your fitness goals through sustainable and practical dietary strategies.',
    icon: 'apple',
    color: 'terracotta',
  },
  {
    id: 9,
    name: 'Yoga Therapy',
    description: 'Therapeutic yoga tailored to your health condition — not a generic fitness class. Addresses chronic pain, stress, flexibility, respiratory conditions and mental wellness through carefully sequenced asanas, pranayama and relaxation techniques.',
    icon: 'sun',
    color: 'bark',
  },
  {
    id: 10,
    name: 'Strength & Conditioning',
    description: 'Structured, evidence-based training programs designed to improve strength, endurance, mobility, power, and overall physical performance. Through personalised assessment and goal-oriented exercise planning, we help athletes, fitness enthusiasts, and individuals of all ages enhance functional movement, prevent injuries, optimise performance, and build long-term physical resilience for a healthier and more active lifestyle.',
    icon: 'dumbbell',
    color: 'sage',
  },
  {
    id: 11,
    name: 'Antenatal & Postnatal Care',
    description: 'Comprehensive physiotherapy and wellness support through every stage of pregnancy and postpartum recovery. Includes pelvic floor rehabilitation, diastasis recti management, posture correction, safe exercise guidance and lactation support.',
    icon: 'heart',
    color: 'terracotta',
  },
  {
    id: 12,
    name: 'Foot Scan Assessment & Treatment',
    description: 'Advanced computerised gait and foot pressure analysis to identify flat feet, high arches, overpronation and biomechanical imbalances. Followed by custom orthotic prescription, targeted foot exercises and footwear guidance.',
    icon: 'footprints',
    color: 'bark',
  },
]

export const BRANCHES = [
  {
    id: 1,
    name: 'Nigdi – Pradhikaran',
    tag: 'Main Branch',
    address: 'Plot No 606, Sector 25, Near Kachghar Chowk, Pradhikaran, Nigdi, Pune – 411044',
    timings: [
      { label: 'Morning', time: '8:30 am – 2:00 pm' },
      { label: 'Evening', time: '5:00 pm – 9:00 pm' },
    ],
    days: 'Mon – Sat',
    phones: ['76669 26099'],
    color: 'sage',
    mapsUrl: 'https://maps.app.goo.gl/7Gt9vg9gEsycqJxj9',
  },
  {
    id: 2,
    name: 'Chinchwad – MIDC',
    tag: 'Branch',
    address: 'RL 143, Pu. La Deshpande Marg, Infront of Ashtvinayak Ganapati Mandir, Shahu Nagar, MIDC, Chinchwad, Pune – 411019',
    timings: [
      { label: 'Morning', time: '10:00 am – 1:00 pm' },
      { label: 'Evening', time: '6:00 pm – 8:30 pm' },
    ],
    days: 'Mon – Sat',
    phones: ['+91 98348 50379'],
    color: 'terracotta',
    mapsUrl: 'https://maps.app.goo.gl/A4bRG8Kru7zyJHR29',
  },
  {
    id: 3,
    name: 'Vishrantwadi',
    tag: 'Branch',
    address: 'Pramod Apartments, 72A, Kasturba Housing Society, Vishrantwadi, Pune – 411015',
    timings: [
      { label: 'Morning', time: '9:30 am – 1:30 pm' },
      { label: 'Evening', time: '6:00 pm – 9:00 pm' },
    ],
    days: 'Mon – Sat',
    phones: ['7798731833', '7276042117'],
    color: 'bark',
    mapsUrl: 'https://maps.app.goo.gl/2p9ikUkB1VPA5YFU8',
  },
  {
    id: 4,
    name: 'Ravet',
    tag: 'Branch',
    address: 'Sr No 184 B/2, 2nd Floor, Behind Madhav Mithas, Shinde Vasti Chowk, Shinde Vasti, Ravet, Pune – 412101',
    timings: [
      { label: 'Morning', time: '10:00 am – 2:00 pm' },
      { label: 'Evening', time: '5:00 pm – 8:30 pm' },
    ],
    days: 'Mon – Sat',
    phones: ['9270582552'],
    color: 'sage',
    mapsUrl: 'https://maps.google.com/?q=Sr+No+184+B2+Shinde+Vasti+Chowk+Ravet+Pune+412101',
  },
]

export const TESTIMONIALS = [
  {
    text: 'Suffered from severe back pain for two years. After just 6 sessions at Aayurphysio, I can finally sit through a full workday without discomfort. The doctors explain everything so patiently.',
    name: 'Rahul K.',
    location: 'Sector 24, Nigdi',
    initials: 'RK',
  },
  {
    text: 'Dr. Amruta guided me through my entire third trimester with exercises and nutrition tips. I had a smooth delivery and recovered in record time. Cannot recommend enough for expecting mothers.',
    name: 'Sneha P.',
    location: 'Pradhikaran, Nigdi',
    initials: 'SP',
  },
  {
    text: 'Post-surgery rehab after my knee replacement was handled brilliantly. The whole team is warm, professional and genuinely invested in your recovery.',
    name: 'Vijay D.',
    location: 'Akurdi, Pune',
    initials: 'VD',
  },
]
